# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/kit-pmd-4.ydns.eu
cert = /etc/letsencrypt/live/kit-pmd-4.ydns.eu/cert.pem
privkey = /etc/letsencrypt/live/kit-pmd-4.ydns.eu/privkey.pem
chain = /etc/letsencrypt/live/kit-pmd-4.ydns.eu/chain.pem
fullchain = /etc/letsencrypt/live/kit-pmd-4.ydns.eu/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 28a4b7c63befb5109c0ed8e086ae5e2a
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
kit-pmd-4.ydns.eu = /var/www/certbot
